name: ride-players
version: "${version}"
main: org.taken.ridePlayers.RidePlayers
api-version: "${apiVersion}"
author: Taken
description: A plugin that allows players to ride each other.
website: https://github.com/Taken/ride-players

commands:
  rideplayer:
    description: Ride another player
    usage: /rideplayer <player> [player]
    permission: rideplayers.ride
  kickplayeroff:
    description: Remove the person riding you
    usage: /kickplayeroff
    permission: rideplayers.kickoff

permissions:
  rideplayers.ride:
    description: Allows riding other players
    default: true
  rideplayers.ride.others:
    description: Allows making other players ride each other
    default: op
  rideplayers.kickoff:
    description: Allows kicking off players riding you
    default: true
